theme: jekyll-theme-minimal
name: Shield Your Info
description: Sharing Internet Privacy and Security Tips
logo: assets/shield your info-01.png
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
twitter:
  username: searchencrypt
  card: summary
facebook:
  publisher: https://www.facebook.com/searchencrypt
social:
  name: Search Encrypt
  links:
    - https://twitter.com/SearchEncrypt
    - https://www.facebook.com/searchencrypt
    - https://www.linkedin.com/company/search-encrypt/
    - https://github.com/SearchEncrypt
google_verify: UUT1ySDRZncZgDUtNSHfXDQjnDrDz640gxl9hD9xQQ4
